[general]
server_check_url = https://cp.cloudflare.com/generate_204
server_check_timeout = 2000
fallback_udp_policy = proxy
udp_whitelist = 53, 123, 443
dns_exclusion_list = *.cmpassport.com, *.jegotrip.com.cn, *.icitymobile.mobi, id6.me

[dns]
no-system
no-ipv6
prefer-doh3
doh-server = https://1.1.1.1/dns-query, https://dns.google/dns-query
server = 223.5.5.5
server = 119.29.29.29

[policy]
static = proxy, auto, direct
url-latency-benchmark = auto, check-interval=300, alive-checking=true, tolerance=20

[server_remote]
https://你的订阅链接, tag=auto, update-interval=86400

[filter_remote]
FILTER_REGION, tag=CN, force-policy=direct, inserted-resource=true
FILTER_LAN, tag=LAN, force-policy=direct, inserted-resource=true

[filter_local]
host-keyword, music.163.com, direct
host-suffix, music.126.net, direct
host-suffix, 163yun.com, direct
host-suffix, netease.com, direct
host-suffix, netease.im, direct

host, iadmat.nosdn.127.net, reject
host, iadmatapk.nosdn.127.net, reject
host, iadmusicmat.music.126.net, reject
host, iadmusicmatvideo.music.126.net, reject

ip-cidr, 10.0.0.0/8, direct
ip-cidr, 127.0.0.0/8, direct
ip-cidr, 172.16.0.0/12, direct
ip-cidr, 192.168.0.0/16, direct
geoip, cn, direct

final, proxy

[rewrite_local]
^https?:\/\/(www.)?(g|google)\.cn url 302 https://www.google.com
^https?:\/\/(ditu|maps).google\.cn url 302 https://maps.google.com

[mitm]
hostname = *.music.163.com
